apiVersion: v1
kind: Namespace
metadata:
  name: flightdeck
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck-token
  namespace: flightdeck
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck
  namespace: flightdeck
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: flightdeck
  template:
    metadata:
      labels:
        k8s-app: flightdeck
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flightdeck
          image: autovia/flightdeck:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
      serviceAccountName: flightdeck
      nodeSelector:
        "kubernetes.io/os": linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck
  namespace: flightdeck
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: flightdeck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck
  namespace: flightdeck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightdeck
subjects:
  - kind: ServiceAccount
    name: flightdeck
    namespace: flightdeck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flightdeck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flightdeck
subjects:
  - kind: ServiceAccount
    name: flightdeck
    namespace: flightdeck
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck
  namespace: flightdeck
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: flightdeck
  name: flightdeck
  namespace: flightdeck
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["flightdeck-token"]
    verbs: ["get", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["flightdeck-settings"]
    verbs: ["get", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: flightdeck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: flightdeck